#!/bin/sh -e

bridges() {
	while read -r LINE; do
		# convert "Bridge [transport] IP:ORPort [fingerprint]"
		# to "IP,ORPort"

		set -- $LINE

		if test "$1" = Bridge; then
			for x in "$2" "$3"; do
				case "$x" in *:*)
					echo ${x%:*},${x#*:}
				esac
			done
		fi
	done <<-END | corridor-load-ipset-relays
		$BRIDGES
	END
}

receive_consensus() {
	if test -n "$TOR_CONTROL_SOCKET"; then
		CTRL=UNIX-CONNECT:$TOR_CONTROL_SOCKET
	else
		CTRL=TCP:${TOR_CONTROL_HOST-localhost}:${TOR_CONTROL_PORT-9051}
	fi

	if test -n "$TOR_CONTROL_COOKIE_AUTH_FILE"; then
		hex()  { perl -ne "print unpack '(H2)*'"; }
		auth() { hex <"$TOR_CONTROL_COOKIE_AUTH_FILE"; }
	else
		auth() { echo "\"$TOR_CONTROL_PASSWD\""; }
	fi

	while :; do
		socat "$CTRL",crnl -,ignoreeof <<-END || :
			AUTHENTICATE `auth`
			GETINFO config/defaults
			GETINFO ns/all
			SETEVENTS NEWCONSENSUS
		END
		sleep 1
	done
}

process_consensus() {
	DIR_AUTHS=

	while read -r LINE; do
		set -- $LINE

		case "$1" in
		DirAuthority)
			ORPORT=
			for s; do
				case "$s" in
				     orport=*) ORPORT=${s#*=} ;;
				   *[!0-9.:]*) continue ;;
				*[0-9]:[0-9]*)
					if test -n "$ORPORT"; then
						DIR_AUTHS="$DIR_AUTHS
						           ${s%:*},$ORPORT"
					fi
				;;
				esac
			done
		;;

		[26]50+*)
			echo Processing router list...
			RELAYS=
		;;

		r)
			IP=$7
			ORPORT=$8
		;;

		s)
			case         "$LINE " in *" Valid "*)
				case "$LINE " in *" Guard "*)
					RELAYS="$RELAYS
					        $IP,$ORPORT"
				esac
			esac
		;;

		.)
			case "$RELAYS" in ?*)
				corridor-load-ipset-relays <<-END
					$DIRECTORY_AUTHORITIES
					$RELAYS
				END
			esac
		;;

		5*)
			echo "$LINE"
			exit 1
		;;
		esac
	done >&2
}


. corridor-load-config

if test -n "$BRIDGES"; then
	bridges
else
	receive_consensus | process_consensus
fi
