#!/bin/sh -e

# SNAT
${1+iptables -t nat -I POSTROUTING -s "$1" ! -d "$1" -j MASQUERADE}

# Don't forward IPv4 traffic unless it comes back from, or goes out to,
# a relay IP:port
IPSET=`corridor-helper-update </dev/null`
iptables -I FORWARD -m conntrack ! --ctstate ESTABLISHED,RELATED \
                    -m set       ! --match-set "$IPSET" dst,dst  \
		    -j REJECT --reject-with icmp-host-prohibited

# Enable IPv4 forwarding in general
sysctl net.ipv4.ip_forward=1

# Disable IPv6 forwarding if the kernel supports IPv6
sysctl net.ipv6.ip_forward=0 || :
