#!/bin/sh -e

receive() {
	while :; do
		socat "$CTRL",crnl -,ignoreeof <<-END
			AUTHENTICATE `auth`
			GETINFO ns/all
			SETEVENTS NEWCONSENSUS
		END
		sleep 1
	done
}

process() {
	while read -r LINE; do
		set -- $LINE

		case "$1" in
		[26]50+*)
			echo Processing router list...
			RELAYS=
		;;

		r)
			IP=$7
			ORPORT=$8
		;;

		s)
			case         "$LINE " in *" Valid "*)
				case "$LINE " in *" Guard "* | *" Authority "*)
					RELAYS="$RELAYS
$IP,$ORPORT"
				esac
			esac
		;;

		.)
			corridor-ipset-relays <<-END
				$RELAYS
			END
		;;

		5*)
			echo "$LINE"
			exit 1
		;;
		esac
	done >&2
}

setup() {
	if test -n "$TOR_CONTROL_SOCKET"; then
		CTRL=UNIX-CONNECT:$TOR_CONTROL_SOCKET
	else
		CTRL=TCP:${TOR_CONTROL_HOST-localhost}:${TOR_CONTROL_PORT-9051}
	fi

	if test -n "$TOR_CONTROL_COOKIE_AUTH_FILE"; then
		hex()  { perl -ne "print unpack '(H2)*'"; }
		auth() { hex <"$TOR_CONTROL_COOKIE_AUTH_FILE"; }
	else
		auth() { echo "\"$TOR_CONTROL_PASSWD\""; }
	fi
}

setup
receive | process
