#!/bin/sh -e

# Ensure that the ipset to be referenced later exists
corridor-ipset-relays --init

# Build a chain and hook it
iptables -N CORRIDOR
iptables -I FORWARD -j CORRIDOR

# Bail out if this is a connection to a relay
iptables -A CORRIDOR -m conntrack --ctstate ESTABLISHED,RELATED       -j RETURN
iptables -A CORRIDOR -m set       --match-set corridor_relays dst,dst -j RETURN

# No packet for you
iptables -A CORRIDOR -j REJECT --reject-with icmp-host-prohibited
