#!/bin/sh -e

# convert "Bridge [transport] IP:ORPort [fingerprint]" lines
# to "IP,ORPort" lines for corridor-load-ipset-relays
while read -r LINE; do
	set -- $LINE

	if test "$1" = Bridge; then
		for x in "$2" "$3"; do
			case "$x" in *:*)
				echo ${x%:*},${x#*:}
			esac
		done
	fi
done | corridor-load-ipset-relays
