#!/bin/sh -e

. corridor-load-config

while read PRIV PUB; do
	if test -n "$PUB"; then
		set SNAT --to-source "$PUB"
	else
		set MASQUERADE
	fi

	iptables -t nat -I POSTROUTING -s "$PRIV" ! -d "$PRIV" -j "$@"
done <<-END
	$SNAT
END
